[package]
name = "data-types"
version = "0.1.0"
authors = ["Francisco Sueza <fcosueza@disroot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
